export const POPULAR_MOVIES_REQUEST = "POPULAR_MOVIES_REQUEST";
export const POPULAR_MOVIES_SUCCESS = "POPULAR_MOVIES_SUCCESS";
export const POPULAR_MOVIES_FAILED = "POPULAR_MOVIES_FAILED";

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";

export const MOVIE_GENRES_REQUEST = "MOVIES_GENRES_REQUEST";
export const MOVIE_GENRES_SUCCESS = "MOVIES_GENRES_SUCCESS";
export const MOVIE_GENRES_FAILED = "MOVIES_GENRES_FAILED";

export const SIMILAR_MOVIES_REQUEST = "SIMILAR_MOVIES_REQUEST";
export const SIMILAR_MOVIES_SUCCESS = "SIMILAR_MOVIES_SUCCESS";
export const SIMILAR_MOVIES_FAILED = "SIMILAR_MOVIES_FAILED";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILED = "MOVIE_DETAILS_FAILED";
