export const POPULAR_MOVIES_REQUEST = "POPULAR_MOVIES_REQUEST";
export const POPULAR_MOVIES_SUCCESS = "POPULAR_MOVIES_SUCCESS";
export const POPULAR_MOVIES_FAILED = "POPULAR_MOVIES_FAILED";

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";

export const MOVIE_GENRES_REQUEST = "MOVIES_GENRES_REQUEST";
export const MOVIE_GENRES_SUCCESS = "MOVIES_GENRES_SUCCESS";
export const MOVIE_GENRES_FAILED = "MOVIES_GENRES_FAILED";

export const SIMILAR_MOVIES_REQUEST = "SIMILAR_MOVIES_REQUEST";
export const SIMILAR_MOVIES_SUCCESS = "SIMILAR_MOVIES_SUCCESS";
export const SIMILAR_MOVIES_FAILED = "SIMILAR_MOVIES_FAILED";

export const MOVIE_DETAILS_REQUEST = "MOVIE_DETAILS_REQUEST";
export const MOVIE_DETAILS_SUCCESS = "MOVIE_DETAILS_SUCCESS";
export const MOVIE_DETAILS_FAILED = "MOVIE_DETAILS_FAILED";

export const SELECT_MOVIE = "SELECT_MOVIE";

export const MOVIES_BY_GENRE_REQUEST = "MOVIES_BY_GENRE_REQUEST";
export const MOVIES_BY_GENRE_SUCCESS = "MOVIES_BY_GENRE_SUCCESS";
export const MOVIES_BY_GENRE_FAILED = "MOVIES_BY_GENRE_FAILED";

export const NOW_PLAYING_MOVIES_REQUEST = "NOW_PLAYING_MOVIES_REQUEST";
export const NOW_PLAYING_MOVIES_SUCCESS = "NOW_PLAYING_MOVIES_SUCCESS";
export const NOW_PLAYING_MOVIES_FAILED = "NOW_PLAYING_MOVIES_FAILED";

export const TOP_RATED_MOVIES_REQUEST = "TOP_RATED_MOVIES_REQUEST";
export const TOP_RATED_MOVIES_SUCCESS = "TOP_RATED_MOVIES_SUCCESS";
export const TOP_RATED_MOVIES_FAILED = "TOP_RATED_MOVIES_FAILED";

export const MOVIE_CREDITS_REQUEST = "MOVIE_CREDITS_REQUEST";
export const MOVIE_CREDITS_SUCCESS = "MOVIE_CREDITS_SUCCESS";
export const MOVIE_CREDITS_FAILED = "MOVIE_CREDITS_FAILED";
