export const MOVIE_TRAILER_REQUEST = "MOVIE_TRAILER_REQUEST";
export const MOVIE_TRAILER_SUCCESS = "MOVIE_TRAILER_SUCCESS";
export const MOVIE_TRAILER_FAILED = "MOVIE_TRAILER_FAILED";

export const RESET_TRAILER_STATE = "RESET_TRAILER_STATE";
